spring:
  profiles:
    active: junit
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

handlebars:
  suffix: .html
  enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subway?serverTimzone=Asia/Seoul
    username: root
    password: masterpw

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.77.142:3306/subway?serverTimzone=Asia/Seoul
    username: root
    password: masterpw
